name: Terraform CI/CD

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ github.ref == 'refs/heads/master' && '<prod account id>' || '061039769350' }}
      AWS_REGION: ap-southeast-1
      ENV: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/TerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      # ---------------- PLAN ----------------
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -var="env=${ENV}" > plan.txt

      - name: Upload Plan as PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt

      # ---------------- APPLY ----------------
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var="env=${ENV}"
